config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: 'letter_opener' if Rails.env.development?

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web, at: 'sidekiq', as: :sidekiq
    mount PgHero::Engine, at: 'pghero', as: :pghero
  end

  use_doorkeeper do
    controllers authorizations: 'oauth/authorizations', authorized_applications: 'oauth/authorized_applications'
  end

  get '.well-known/host-meta', to: 'well_known/host_meta#show', as: :host_meta, defaults: { format: 'xml' }
  get '.well-known/webfinger', to: 'well_known/webfinger#show', as: :webfinger

  devise_for :users, path: 'auth', controllers: {
    sessions:           'auth/sessions',
    registrations:      'auth/registrations',
    passwords:          'auth/passwords',
    confirmations:      'auth/confirmations',
  }

  get '/users/:username', to: redirect('/@%{username}'), constraints: { format: :html }

  resources :accounts, path: 'users', only: [:show], param: :username do
    resources :stream_entries, path: 'updates', only: [:show] do
      member do
        get :embed
      end
    end

    get :remote_follow,  to: 'remote_follow#new'
    post :remote_follow, to: 'remote_follow#create'

    resources :followers, only: [:index], controller: :follower_accounts
    resources :following, only: [:index], controller: :following_accounts
    resource :follow, only: [:create], controller: :account_follow
    resource :unfollow, only: [:create], controller: :account_unfollow
  end

  get '/@:username', to: 'accounts#show', as: :short_account
  get '/@:account_username/:id', to: 'statuses#show', as: :short_account_status

  namespace :settings do
    resource :profile, only: [:show, :update]
    resource :preferences, only: [:show, :update]
    resource :import, only: [:show, :create]

    resource :export, only: [:show]
    namespace :exports, constraints: { format: :csv } do
      resources :follows, only: :index, controller: :following_accounts
      resources :blocks, only: :index, controller: :blocked_accounts
      resources :mutes, only: :index, controller: :muted_accounts
    end

    resource :two_factor_authentication, only: [:show, :create, :destroy]
    namespace :two_factor_authentication do
      resources :recovery_codes, only: [:create]
      resource :confirmation, only: [:new, :create]
    end

    resource :follower_domains, only: [:show, :update]
  end

  resources :media, only: [:show]
  resources :tags,  only: [:show]

  # Remote follow
  get  :authorize_follow, to: 'authorize_follow#new'
  post :authorize_follow, to: 'authorize_follow#create'

  namespace :admin do
    resources :pubsubhubbub, only: [:index]
    resources :domain_blocks, only: [:index, :new, :create, :show, :destroy]
    resources :settings, only: [:index, :update]
    resources :instances, only: [:index]

    resources :reports, only: [:index, :show, :update] do
      resources :reported_statuses, only: :destroy
    end

    resources :accounts, only: [:index, :show] do
      resource :reset, only: [:create]
      resource :silence, only: [:create, :destroy]
      resource :suspension, only: [:create, :destroy]
      resource :confirmation, only: [:create]
    end
  end

  get '/admin', to: redirect('/admin/settings', status: 302)

  namespace :api do
    # PubSubHubbub outgoing subscriptions
    resources :subscriptions, only: [:show]
    post '/subscriptions/:id', to: 'subscriptions#update'

    # PubSubHubbub incoming subscriptions
    post '/push', to: 'push#update', as: :push

    # Salmon
    post '/salmon/:id', to: 'salmon#update', as: :salmon

    # OEmbed
    get '/oembed', to: 'oembed#show', as: :oembed

    # ActivityPub
    namespace :activitypub do
      get '/users/:id/outbox', to: 'outbox#show', as: :outbox
      get '/statuses/:id', to: 'activities#show_status', as: :status
      resources :notes, only: [:show]
    end

    # JSON / REST API
    namespace :v1 do
      resources :statuses, only: [:create, :show, :destroy] do
        member do
          get :context
          get :card
          get :reblogged_by
          get :favourited_by

          post :reblog
          post :unreblog
          post :favourite
          post :unfavourite
        end
      end

      get '/timelines/home',     to: 'timelines#home', as: :home_timeline
      get '/timelines/public',   to: 'timelines#public', as: :public_timeline
      get '/timelines/tag/:id',  to: 'timelines#tag', as: :hashtag_timeline

      get '/search', to: 'search#index', as: :search

      resources :follows,    only: [:create]
      resources :media,      only: [:create]
      resources :apps,       only: [:create]
      resources :blocks,     only: [:index]
      resources :mutes,      only: [:index]
      resources :favourites, only: [:index]
      resources :reports,    only: [:index, :create]

      resource :instance, only: [:show]

      resources :follow_requests, only: [:index] do
        member do
          post :authorize
          post :reject
        end
      end

      resources :notifications, only: [:index, :show] do
        collection do
          post :clear
          post :dismiss
        end
      end

      resources :accounts, only: [:show] do
        collection do
          get :relationships
          get :verify_credentials
          patch :update_credentials
          get :search
        end

        member do
          get :statuses
          get :followers
          get :following

          post :follow
          post :unfollow
          post :block
          post :unblock
          post :mute
          post :unmute
        end
      end
    end

    namespace :web do
      resource :settings, only: [:update]
    end
  end

  get '/web/(*any)', to: 'home#index', as: :web

  get '/about',      to: 'about#show'
  get '/about/more', to: 'about#more'
  get '/terms',      to: 'about#terms'

  root 'home#index'

  match '*unmatched_route',
    via: :all,
    to: 'application#raise_not_found',
    format: false
end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  before_action :set_body_classes
  before_action :set_instance_presenter, only: [:show, :more]

  def show; end

  def more; end

  def terms; end

  private

  def new_user
    User.new.tap(&:build_account)
  end
  helper_method :new_user

  def set_instance_presenter
    @instance_presenter = InstancePresenter.new
  end

  def set_body_classes
    @body_classes = 'about-body'
  end
end

app/views/about/_contact.html.haml
.panel
  .panel-header= t 'about.contact'
  .panel-body
    - if contact.contact_account
      .owner
        .avatar= image_tag contact.contact_account.avatar.url
        .name
          = link_to TagManager.instance.url_for(contact.contact_account) do
            %span.display_name.emojify= display_name(contact.contact_account)
            %span.username= "@#{contact.contact_account.acct}"

    - if contact.site_contact_email
      .contact-email
        = t 'about.business_email'
        %strong= contact.site_contact_email

app/views/about/_links.html.haml
.panel
  .panel-header= t 'about.links'
  .panel-list
    %ul
      - if user_signed_in?
        %li= link_to t('about.get_started'), root_path
      - else
        %li= link_to t('about.get_started'), new_user_registration_path
        %li= link_to t('auth.login'), new_user_session_path
      %li= link_to t('about.terms'), terms_path
      %li= link_to t('about.source_code'), 'https://github.com/tootsuite/mastodon'

app/views/about/_registration.html.haml
= simple_form_for(new_user, url: user_registration_path) do |f|
  = f.simple_fields_for :account do |account_fields|
    = account_fields.input :username,
      autofocus: true,
      placeholder: t('simple_form.labels.defaults.username'),
      required: true,
      input_html: { 'aria-label' => t('simple_form.labels.defaults.username') }

  = f.input :email,
    placeholder: t('simple_form.labels.defaults.email'),
    required: true,
    input_html: { 'aria-label' => t('simple_form.labels.defaults.email') }
  = f.input :password,
    autocomplete: "off",
    placeholder: t('simple_form.labels.defaults.password'),
    required: true,
    input_html: { 'aria-label' => t('simple_form.labels.defaults.password') }
  = f.input :password_confirmation,
    autocomplete: "off",
    placeholder: t('simple_form.labels.defaults.confirm_password'),
    required: true,
    input_html: { 'aria-label' => t('simple_form.labels.defaults.confirm_password') }

  .actions
    = f.button :button, t('about.get_started'), type: :submit

  .info
    = link_to t('auth.login'), new_user_session_path, class: 'webapp-btn'
    ·
    = link_to t('about.about_this'), about_more_path

app/views/about/_version.html.haml
.panel
  .panel-header= t 'about.version'
  .panel-body
    %strong= version.version_number

app/views/about/more.html.haml
- content_for :page_title do
  = site_hostname

.wrapper.thicc
  .sidebar-layout
    .main
      .panel
        %h2= site_hostname

        - unless @instance_presenter.site_description.blank?
          %p= @instance_presenter.site_description.html_safe

      .information-board
        .section
          %span= t 'about.user_count_before'
          %strong= number_with_delimiter @instance_presenter.user_count
          %span= t 'about.user_count_after'
        .section
          %span= t 'about.status_count_before'
          %strong= number_with_delimiter @instance_presenter.status_count
          %span= t 'about.status_count_after'
        .section
          %span= t 'about.domain_count_before'
          %strong= number_with_delimiter @instance_presenter.domain_count
          %span= t 'about.domain_count_after'

      - unless @instance_presenter.site_extended_description.blank?
        .panel= @instance_presenter.site_extended_description.html_safe

    .sidebar
      = render 'contact', contact: @instance_presenter
      = render 'links'
      = render 'version', version: @instance_presenter

app/views/about/show.html.haml
- content_for :header_tags do
  = javascript_include_tag 'application_public', integrity: true, crossorigin: 'anonymous'

- content_for :page_title do
  = site_hostname

- content_for :header_tags do
  %meta{ property: 'og:site_name', content: site_title }/
  %meta{ property: 'og:url', content: about_url }/
  %meta{ property: 'og:type', content: 'website' }/
  %meta{ property: 'og:title', content: site_hostname }/
  %meta{ property: 'og:description', content: strip_tags(@instance_presenter.site_description.presence || t('about.about_mastodon')) }/
  %meta{ property: 'og:image', content: asset_url('mastodon_small.jpg') }/
  %meta{ property: 'og:image:width', content: '400' }/
  %meta{ property: 'og:image:height', content: '400' }/
  %meta{ property: 'twitter:card', content: 'summary' }/

.wrapper
  %h1
    = image_tag 'logo.png'
    = Setting.site_title

  %p= t('about.about_mastodon').html_safe

  .screenshot-with-signup
    .mascot= image_tag 'fluffy-elephant-friend.png'

    - if @instance_presenter.open_registrations
      = render 'registration'
    - else
      .closed-registrations-message
        - if @instance_presenter.closed_registrations_message.blank?
          %p= t('about.closed_registrations')
        - else
          = @instance_presenter.closed_registrations_message.html_safe
        .info
          = link_to t('auth.login'), new_user_session_path, class: 'webapp-btn'
          ·
          = link_to t('about.other_instances'), 'https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/List-of-Mastodon-instances.md'
          ·
          = link_to t('about.about_this'), about_more_path

  %h3= t('about.features_headline')

  .features-list
    .features-list__column
      %ul.fa-ul
        %li
          = fa_icon('li check-square')
          = t 'about.features.chronology'
        %li
          = fa_icon('li check-square')
          = t 'about.features.public'
        %li
          = fa_icon('li check-square')
          = t 'about.features.characters'
        %li
          = fa_icon('li check-square')
          = t 'about.features.gifv'
    .features-list__column
      %ul.fa-ul
        %li
          = fa_icon('li check-square')
          = t 'about.features.privacy'
        %li
          = fa_icon('li check-square')
          = t 'about.features.blocks'
        %li
          = fa_icon('li check-square')
          = t 'about.features.ethics'
        %li
          = fa_icon('li check-square')
          = t 'about.features.api'

  - unless @instance_presenter.site_description.blank?
    %h3= t('about.description_headline', domain: site_hostname)
    %p= @instance_presenter.site_description.html_safe

  .actions
    .info
      = link_to t('about.terms'), terms_path
      ·
      = link_to t('about.apps'), 'https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/Apps.md'
      ·
      = link_to t('about.source_code'), 'https://github.com/tootsuite/mastodon'
      ·
      = link_to t('about.other_instances'), 'https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/List-of-Mastodon-instances.md'

app/views/about/terms.en.html.haml
- content_for :page_title do
  #{site_hostname} Terms of Service and Privacy Policy

.wrapper
  %h2 Privacy Policy

  %h3#collect What information do we collect?

  %p We collect information from you when you register on our site and gather data when you participate in the forum by reading, writing, and evaluating the content shared here.

  %p When registering on our site, you may be asked to enter your name and e-mail address. You may, however, visit our site without registering. Your e-mail address will be verified by an email containing a unique link. If that link is visited, we know that you control the e-mail address.

  %p When registered and posting, we record the IP address that the post originated from. We also may retain server logs which include the IP address of every request to our server.

  %h3#use What do we use your information for?

  %p Any of the information we collect from you may be used in one of the following ways:

  %ul
    %li To personalize your experience &mdash; your information helps us to better respond to your individual needs.
    %li To improve our site &mdash; we continually strive to improve our site offerings based on the information and feedback we receive from you.
    %li To improve customer service &mdash; your information helps us to more effectively respond to your customer service requests and support needs.
    %li To send periodic emails &mdash; The email address you provide may be used to send you information, notifications that you request about changes to topics or in response to your user name, respond to inquiries, and/or other requests or questions.

  %h3#protect How do we protect your information?

  %p We implement a variety of security measures to maintain the safety of your personal information when you enter, submit, or access your personal information.

  %h3#data-retention What is your data retention policy?

  %p We will make a good faith effort to:

  %ul
    %li Retain server logs containing the IP address of all requests to this server no more than 90 days.
    %li Retain the IP addresses associated with registered users and their posts no more than 5 years.

  %h3#cookies Do we use cookies?

  %p Yes. Cookies are small files that a site or its service provider transfers to your computer's hard drive through your Web browser (if you allow). These cookies enable the site to recognize your browser and, if you have a registered account, associate it with your registered account.

  %p We use cookies to understand and save your preferences for future visits and compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools in the future. We may contract with third-party service providers to assist us in better understanding our site visitors. These service providers are not permitted to use the information collected on our behalf except to help us conduct and improve our business.

  %h3#disclose Do we disclose any information to outside parties?

  %p We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information. This does not include trusted third parties who assist us in operating our site, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others rights, property, or safety. However, non-personally identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.

  %h3#third-party Third party links

  %p Occasionally, at our discretion, we may include or offer third party products or services on our site. These third party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.

  %h3#coppa Children's Online Privacy Protection Act Compliance

  %p
    Our site, products and services are all directed to people who are at least 13 years old. If this server is in the USA, and you are under the age of 13, per the requirements of COPPA
    = surround '(', '),' do
      = link_to 'Children\'s Online Privacy Protection Act', 'https://en.wikipedia.org/wiki/Children%27s_Online_Privacy_Protection_Act'
    do not use this site.

  %h3#online Online Privacy Policy Only

  %p This online privacy policy applies only to information collected through our site and not to information collected offline.

  %h3#consent Your Consent

  %p By using our site, you consent to our web site privacy policy.

  %h3#changes Changes to our Privacy Policy

  %p If we decide to change our privacy policy, we will post those changes on this page.

  %p This document is CC-BY-SA. It was last updated May 31, 2013.

  %p
    Originally adapted from the
    = succeed '.' do
      = link_to 'Discourse privacy policy', 'https://github.com/discourse/discourse'

app/views/about/terms.no.html.haml
- content_for :page_title do
  #{site_hostname} Personvern og villkår for bruk av nettstedet

.wrapper
  %h2 Personvernserklæring

  %h3#collect Hvilke opplysninger samler vi?

  %p Vi samler opplysninger fra deg når du registrerer deg på nettstedet vårt, og vi samler data når du deltar på forumet ved å lese, skrive og evaluere innholdet som deles her.

  %p Når du registrerer deg på nettstedet vårt, kan du bli bedt om å oppgi navnet og e-postadressen din. Imidlertid kan du besøke nettstedet vårt uten å registrere deg. E-postadressen din vil bli bekreftet med en e-post som inneholder en unik lenke. Hvis siden den lenker til, blir besøkt, vet vi at du har kontroll over e-postadressen.

  %p Når du registrerer deg og skriver innlegg, registrerer vi IP-adressen som innlegget stammer fra. Vi kan også oppbevare logger som inkluderer IP-adressen til alle forespørslene sendt til tjeneren vår.

  %h3#use Hva bruker vi opplysningene dine til?

  %p Alle opplysningene vi samler fra deg, kan bli brukt på en av følgende måter:

  %ul
    %li For å gjøre opplevelsen din mer personlig. Opplysningene dine hjelper oss å svare bedre på dine individuelle behov.
    %li For å forbedre nettstedet vårt. Vi jobber konstant for å forbedre nettstedets tilbud basert på opplysningene og tilbakemeldingene vi mottar fra deg.
    %li For å forbedre vår kundeservice. Dine opplysninger hjelper oss å svare mer effektivt på dine forespørsler sendt til kundeservice eller behov om støtte.
    %li For å sende periodiske e-poster. E-postadressen du oppgir, kan bli brukt til å sende deg informasjon, påminnelser som du ber om ved endringer av emner eller ved svar til brukernavnet ditt, til henvendelser, og/eller andre forspørsler eller andre spørsmål.

  %h3#protect Hvordan sikrer vi opplysningene?

  %p Vi gjennomfører flere sikkerhetstiltak for å holde personopplysningene dine sikre når du skriver inn, lagrer eller henter dem.

  %h3#data-retention Hva er retningslinjene deres for lagring av data?

  %p Vi vil forsøke i god tro å:

  %ul
    %li Ikke oppbevare tjener-logger som inneholder IP-adressen til alle forespørslene til denne tjeneren i lenger enn i 90 dager.
    %li Ikke oppbevare IP-adressene forbundet med registrerte brukere og deres innlegg lenger enn i 5 år.

  %h3#cookies Bruker vi informasjonskapsler?

  %p Ja. Informasjonskapsler er små filer som et nettsted eller dets tjenesteleverandør overfører til harddisken på datamaskinen din gjennom nettleseren din (dersom du tillater det). Disse informasjonskapslene gjør det mulig for nettstedet å gjenkjenne nettleseren din og, dersom du har en konto, knytte nettleseren til den.

  %p Vi bruker informasjonskapsler for å forstå og lagre preferansene dine for fremtidige besøk og for å samle aggregatdata om trafikk på og samhandling med nettstedet slik at vi kan tilby bedre opplevelser og verktøy på nettstedet i fremtiden. Vi kan inngå avtaler med tredjeparts tjenesteleverandører for å bistå oss i å forstå besøkerne våres bedre. Disse tjenesteleverandørene har ikke lov til å bruke opplysningene samlet på våres vegne unntatt til å hjelpe oss å gjennomføre og forbedre anliggendet vårt.

  %h3#disclose Gir vi noen opplysninger videre til andre parter?

  %p Vi verken selger, handler med eller overfører på noen annen måte til andre parter dine identifiserbare personopplysninger. Dette inkluderer ikke tredjeparter som har vår tillit og bistår oss i å drive nettstedet, utføre våre anliggender eller yter tjenester til deg, så lenge disse partene samtykker til å behandle disse opplysningene fortrolig. Vi kan også frigi opplysningene dine dersom vi tror at å frigi dem er hensiktsmessig for å overholde loven, håndheve nettstedet retningslinjer eller beskytte våre og andres rettigheter. Imidlertid kan opplysninger som ikke er personlig identifiserbare, bli delt med andre parter for markedsføring, reklame eller annet bruk.

  %h3#third-party Tredjeparts lenker

  %p Av og til, etter skjønn, kan vil inkludere eller tilby tredjeparts produkter eller tjenester på nettstedet vårt. Disse tredjeparts nettstedene har separate og selvstendige personvernerklæringer. Vi bærer derfor intet ansvar eller forpliktelser for innholdet eller aktivitetene til disse nettstedene det lenkes til. Ikke mindre prøver vi å bevare vår eget nettsteds integritet og ønsker enhver tilbakemelding om disse nettstedene velkomne.

  %h3#coppa Overensstemmelse med Children's Online Privacy Protection Act

  %p
    Nettstedet er rettet mot folk som er minst 13 år gamle. Dersom denne tjeneren er i USA, og du er under 13 år i henhold til kravene i  COPPA
    = surround '(', '),' do
      = link_to 'Children\'s Online Privacy Protection Act', 'https://en.wikipedia.org/wiki/Children%27s_Online_Privacy_Protection_Act'
    ikke bruk dette nettstedet.

  %h3#online Personvernerklæring bare for nettet

  %p Denne nett-personvernerklæringen gjelder bare for informasjon samlet gjennom nettstedet vårt og ikke for opplysninger samlet når en er frakoblet.

  %h3#consent Ditt samtykke

  %p Ved å bruke dette nettstedet samtykker du til nettstedets personvernerklæring.

  %h3#changes Endringer i vår personvernerklæring

  %p Dersom vi beslutter å endre personvernerklæringen vår, vil vi publisere disse endringene på denne siden.

  %p Dette dokumentet er lisensiert under CC-BY-SA. De ble sist oppdatert 12. april 2017.

  %p
    Dokumentet er en adoptert og endret versjon fra
    = succeed '.' do
      = link_to 'Discourse privacy policy', 'https://github.com/discourse/discourse'